name: Automatisation des tests

on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & tests CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure

  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run test car + create report
        run: |
          mkdir reports
          echo "=== Rapport Test Fonction CAR (Carré) ===" > reports/rapport_car.txt
          echo "Date : $(date)" >> reports/rapport_car.txt
          echo "Commande : ./src/calculator car 5" >> reports/rapport_car.txt
          echo -n "Résultat : " >> reports/rapport_car.txt
          cd build
          ./src/calculator car 5 | tee -a ../reports/rapport_car.txt

      - name: Upload artefact rapport CAR
        uses: actions/upload-artifact@v4
        with:
          name: rapport-test-car
          path: reports/rapport_car.txt
